## Basic Configuration

baseURL = 'https://www.kamo22sima.com'
languageCode = 'ja'
title = 'かものブログ'
theme = 'hugo-goa'
author = 'Masaya Nakashima'
publishdir = 'docs'
contentdir = 'content'

## Hugo Built-in Features
disqusShortname = '//www-kamo22sima-com.disqus.com/count.js'
googleAnalytics = 'G-YBVNWRBVHF'
enableRobotsTXT = true

## Site Settings
[params]
author = "かも"
intro = ""
description = "高専卒のエンジニア　気ままにしてます"
authorimage = "kamo.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "高専卒のエンジニアがたまに書いているブログです"
keyword = "kamo,blog,かも,ブログ"

## Social Accounts
[params.social]
github = "nakashimamasaya"
twitter = "kamo22sima"
facebook = "kawa18sima"

## Extras
[params.extra]
copyright = "© 2021. Masaya Nakashima." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "https://www.wantedly.com/id/kamo22sima"
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "result"
    identifier = "result"
    weight = 300
    url = "/result/"
